name: 'kingdudely/remote-desktop'
description: 'Debug your GitHub workflow with this action!'

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v7
      with:
        node-version: 24

    - name: Linux setup
      if: runner.os == 'Linux'
      shell: bash --noprofile --norc -euo pipefail {0}
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          jwm \
          xvfb \
          libxtst-dev

        read -r DISPLAY_NUMBER < <(exec Xvfb -displayfd 1 -screen 0 1920x1080x24 +extension XTEST -nolisten tcp)

        export DISPLAY=":$DISPLAY_NUMBER"
        echo "DISPLAY=$DISPLAY" >> "$GITHUB_ENV"
        echo "ELECTRON_DISABLE_SANDBOX=1" >> $GITHUB_ENV

        jwm &

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v4

    - name: Start server
      shell: bash --noprofile --norc -euo pipefail {0}
      working-directory: ${{ github.action_path }}
      run: |
        npm install
        npm start # cloudflared tunnel --metrics "localhost:${METRICS_PORT}" ready