name: Run 9remote

on:
  workflow_dispatch:
    inputs:
      runner_os:
        description: "Runner OS"
        required: true
        default: "macos-latest"
        type: choice
        options:
          - macos-latest
          - ubuntu-latest
          - windows-latest

jobs:
  run-9remote:
    runs-on: ${{ github.event.inputs.runner_os }}
    timeout-minutes: 360

    steps:
      - name: Start virtual display (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb xfce4 xfce4-goodies dbus-x11
 
          PIPE=$(mktemp -u)
          mkfifo "$PIPE"
          Xvfb -displayfd 3 -screen 0 1920x1080x24 3>"$PIPE" &
          echo "DISPLAY=:$(head -1 "$PIPE")" >> $GITHUB_ENV
          rm "$PIPE"

      - name: Start 9remote
        shell: bash
        run: |
          npx 9remote start