name: Main

on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: 'Operating system'
        options:
        - ubuntu
        - windows
        - macos
        default: ubuntu
        required: true

jobs:
  vm:
    runs-on: ${{ github.event.inputs.os }}-latest
    timeout-minutes: 360
    defaults:
      run:
        shell: bash

    steps:
      - name: Install 9remote
        run: npm install -g 9remote

      - name: Run 9remote
        run: 9remote
