name: Check MacOS permissions (AMFI + SIP)

on: 
  push:

jobs:
  remote:
    runs-on: macos-latest
    timeout-minutes: 1
    defaults:
      run:
        shell: bash

    steps:
      - name: AMFI
        run: nvram boot-args

      - name: SIP
        run: csrutil status