name: Check CoreHID HIDVirtualDevice

on:
  push:
  workflow_dispatch:

jobs:
  check-corehid:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@main

      - name: Check SIP status
        run: csrutil status

      - name: Try creating a HIDVirtualDevice
        run: |
          clang++ -std=c++17 -framework IOKit -framework CoreFoundation -framework Cocoa $GITHUB_WORKSPACE/host/macos.cpp -o virtual_mouse
          sudo ./virtual_mouse

      - name: macOS & Xcode version info
        run: |
          sw_vers
          xcodebuild -version