name: nat-filtering-check

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  workflow_dispatch:

jobs:
  listen:
    runs-on: ubuntu-latest
    steps:
      - name: Linux setup
        if: runner.os == 'Linux'
        run: |
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo "deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update && sudo apt-get install cloudflared -y

      - name: MacOS setup
        if: runner.os == 'macOS'
        run: |
          brew install cloudflared

      - name: Windows setup
        if: runner.os == 'Windows'
        run: |
          winget install -e --id=Cloudflare.cloudflared --accept-package-agreements --accept-source-agreements --disable-interactivity

      - name: Cloudflare tunnel
        run: |
          cloudflared tunnel --metrics localhost:60123 --url http://localhost:8080 &
          until cloudflared tunnel --metrics localhost:60123 ready; do
            sleep 0.5
          done
          TUNNEL_URL=$(curl -s http://localhost:60123/quicktunnel | jq -r '.hostname')
          touch "${TUNNEL_URL}"
          echo "url=${TUNNEL_URL}" >> "${GITHUB_OUTPUT}"
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.step.outputs.url }}
          archive: false

      - run: sleep 21600