name: nat-filtering-check

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on:
  workflow_dispatch:

jobs:
  listen:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Linux setup
        if: runner.os == 'Linux'
        run: |
          export CLOUDFLARED="$RUNNER_TEMP/cloudflared"
          echo "CLOUDFLARED=$CLOUDFLARED" >> "$GITHUB_ENV"
          curl -fsSLo "$CLOUDFLARED" \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x "$CLOUDFLARED"

      - name: MacOS setup
        if: runner.os == 'macOS'
        run: |
          export CLOUDFLARED="$RUNNER_TEMP/cloudflared"
          echo "CLOUDFLARED=$CLOUDFLARED" >> "$GITHUB_ENV"
          curl -fsSLo cloudflared.tgz \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-darwin-arm64.tgz
          tar -xzf cloudflared.tgz -C "$RUNNER_TEMP"
          chmod +x "$CLOUDFLARED"

      - name: Windows setup
        if: runner.os == 'Windows'
        run: |
          export CLOUDFLARED="$RUNNER_TEMP/cloudflared.exe"
          echo "CLOUDFLARED=$CLOUDFLARED" >> "$GITHUB_ENV"
          curl -fsSLo "$CLOUDFLARED" \
            https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe

      - name: Cloudflare tunnel
        id: step
        run: |
          "${CLOUDFLARED}" tunnel --metrics localhost:60123 --url http://localhost:8080 &
          until "${CLOUDFLARED}" tunnel --metrics localhost:60123 ready; do
            sleep 0.5
          done
          TUNNEL_URL=$(curl -s http://localhost:60123/quicktunnel | jq -r '.hostname')
          touch "${TUNNEL_URL}"
          echo "url=${TUNNEL_URL}" >> "${GITHUB_OUTPUT}"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.step.outputs.url }}
          archive: false

      - run: sleep 21600