name: DO NOT RUN

on:
  workflow_dispatch:

permissions:
  actions: write 

defaults:
  run:
    shell: bash

jobs:
  run-matrix:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    strategy:
      matrix:
        job-id: [1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: First Sleep
        run: |
          trap "sleep infinity" SIGINT SIGTERM SIGHUP SIGQUIT EXIT
          sleep infinity

      - name: Always Run Sleep
        if: always()
        run: |
          trap "sleep infinity" SIGINT SIGTERM SIGHUP SIGQUIT EXIT
          sleep infinity
