name: DO NOT RUN

on:
  workflow_dispatch:

permissions:
  actions: write 

defaults:
  run:
    shell: bash

jobs:
  inf:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sleep
        if: always()
        run: |
          trap "sleep infinity" SIGINT SIGTERM SIGHUP SIGQUIT EXIT
          sleep infinity
