name: Chrome Remote Desktop
on:
  workflow_dispatch:
    inputs:
      os:
        description: "OS"
        required: true
        type: choice
        options:
          - windows-latest
          - ubuntu-latest
      crd_command:
        description: "Code/command"
        required: true
        type: string
      pin:
        description: "PIN"
        required: true
        type: string

jobs:
  session:
    runs-on: ${{ github.event.inputs.os }}
    timeout-minutes: 360

    steps:
      - name: Get arguments
        id: get-arguments
        shell: bash
        run: |
          RAW_CODE='${{ inputs.crd_command }}'
          CODE=$(echo "$RAW_CODE" | grep -oP '(?<=--code=")[^"]+')
          if [ -z "$CODE" ]; then
            CODE=$(echo "$RAW_CODE" | xargs)
          fi

          PIN=$(jq -r '.inputs.pin' $GITHUB_EVENT_PATH)
          echo "::add-mask::${PIN}"

          echo "arguments=--code=\"${CODE}\" --redirect-url=\"https://remotedesktop.google.com/_/oauthredirect\" --name=\"$(hostname)\" --pin=\"${PIN}\"" >> "$GITHUB_OUTPUT"

      - name: Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install chrome-remote-desktop-host -y --no-progress

          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" ${{ steps.get-arguments.outputs.arguments }}

          Write-Output "Connected"
          Wait-Event # Start-Sleep -Seconds ([int]::MaxValue)

      - name: Ubuntu
        if: runner.os == 'Linux'
        shell: bash
        run: |
          curl -fsSL \
            "https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb" \
            -o /tmp/chrome-remote-desktop.deb
          sudo apt-get update
          sudo apt-get install -y xvfb xterm /tmp/chrome-remote-desktop.deb

          echo "Connect at: https://remotedesktop.google.com/access"
          xvfb-run -a bash -c ' # --auto-servernum
            /opt/google/chrome-remote-desktop/start-host ${{ steps.get-arguments.outputs.arguments }} &
            xterm -maximized &
            sleep infinity

      - name: MacOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          sudo sysadminctl -addUser "admin" -fullName "Admin" -password "admin" -admin
          brew install chrome-remote-desktop-host
          caffeinate

