name: Generate new fingerprint

on:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Generate certificate and fingerprint
        run: |
          openssl req -x509 -newkey rsa:2048 -keyout workflow_key.pem -out workflow_cert.pem \
            -nodes -subj "/CN=WebRTC-Workflow" -days 36500

          FINGERPRINT=$(openssl x509 -in workflow_cert.pem -noout -fingerprint -sha256 | grep -oP '(?<==).*')
          jq --arg fp "$FINGERPRINT" '.workflowFingerprint = $fp' public/constants.json > public/tmp.json && mv public/tmp.json public/constants.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@latest
        with:
          github_token: ${{ github.token }}
          publish_dir: ./public