name: webrtcsink

on:
  workflow_dispatch:
    inputs:
      os:
        description: Operating system
        required: true
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  main:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/checkout@main

      - name: Setup GStreamer
        shell: bash
        env:
          WHEPSERVERSINK_PIPELINE: '! videoconvert ! queue ! whepserversink signaller::host-addr="http://0.0.0.0:8080" signaller::stun-server="stun://stun.l.google.com:19302"'
        run: |
          set -euo pipefail

          case "${RUNNER_OS}" in
            Linux)
              sudo apt-get update
              sudo apt-get install -y \
                gstreamer1.0-tools \
                gstreamer1.0-plugins-base \
                gstreamer1.0-plugins-good \
                gstreamer1.0-plugins-bad \
                gstreamer1.0-plugins-ugly \
                lxqt \
                openbox \
                dbus-x11 \
                xvfb
              
              xvfb-run -as "-screen 0 1920x1080x24" bash -c '
                dbus-launch --exit-with-session startlxqt &
                gst-launch-1.0 \
                  ximagesrc use-damage=0 ${WHEPSERVERSINK_PIPELINE}
              '
              
              ;;
            macOS)
              brew update
              brew install \
                gstreamer \
                gst-plugins-base \
                gst-plugins-good \
                gst-plugins-bad \
                gst-plugins-ugly

              gst-launch-1.0 \
                avfvideosrc capture-screen=true ${WHEPSERVERSINK_PIPELINE}
              ;;
            Windows)
              choco install -y gstreamer

              "/c/Program Files/gstreamer/1.0/msvc_x86_64/bin/gst-launch-1.0.exe" -e \
                d3d11screencapturesrc ${WHEPSERVERSINK_PIPELINE}
              ;;
            *)
              echo "Unsupported operating system: ${RUNNER_OS}"
              exit 1
              ;;
          esac

      - name: Establish tunnel
        id: tunnel
        uses: anyvm-org/cf-tunnel@v0
        with:
          protocol: http
          port: 8080

      - name: Use tunnel
        run: |
          echo "Tunnel URL: https://${{ steps.tunnel.outputs.server }}"
          sleep 21600