on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - shell: bash
        run: |
          echo "${CC}"
          pacman -S mingw-w64-x86_64-x264 mingw-w64-x86_64-pkg-config
