on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - shell: bash
        run: |
          which pacman || echo "pacman not in PATH"
          pacman --version || true
          which pacman.exe || echo "pacman not in PATH"
          pacman.exe --version || true