on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - shell: bash
        run: |
          ls "/c/npm"
          ls "/c/msys64/usr/bin/"
          ls "/c/Users/runneradmin/AppData/Local/"