name: mac

on:
  workflow_dispatch:
    inputs:
      password:
        description: "Password"
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 360

    env:
      VNC_PORT: 5901
      NOVNC_PORT: 6080

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Tools & Dependencies
        run: |
          brew install git python cloudflared libvncserver cmake
          git clone https://github.com/novnc/noVNC.git

      - name: Start VNC Server
        run: |
          chmod +x ./macVNC
          ./macVNC -rfbport "${VNC_PORT}" -passwd "${{ github.event.inputs.password }}" &

          until nc -z -G 1 localhost "${VNC_PORT}" &>/dev/null; do
            sleep 1
          done

      - name: Launch noVNC Proxy
        run: |
          cd noVNC
          echo "[*] Starting noVNC proxy..."
          nohup ./utils/novnc_proxy \
            --vnc "localhost:${VNC_PORT}" \
            --listen "${NOVNC_PORT}" &

          until nc -z -G 1 localhost "${NOVNC_PORT}" &>/dev/null; do
            sleep 1
          done

      - name: Start tunnel
        run: |
          cloudflared tunnel --url "http://localhost:${NOVNC_PORT}" 2>&1 | grep --line-buffered -o 'https://[^ ]*trycloudflare.com'
