name: macOS Browser Remote Desktop

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password'
        required: true

jobs:
  remote-desktop:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Enable Apple VNC
        run: |
          sudo sysadminctl -addUser vncuser \
            -fullName "VNC User" \
            -password "${{ github.event.inputs.password }}" \
            -admin
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes

          printf '%s\n' "${{ github.event.inputs.password }}" \
          | perl -we '
            BEGIN { @k = unpack "C*", pack "H*", "1734516E8BA8C5E2FF1C39567390ADCA" }
            $_ = <>; chomp; s/^(.{8}).*/$1/;
            @p = unpack "C*", $_;
            foreach (@k) { printf "%02X", $_ ^ (shift @p || 0) }
            print "\n";
          ' | sudo tee /Library/Preferences/com.apple.VNCSettings.txt

          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -restart -agent -console
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate

      - name: Start novnc
        run: |
          pip3 install websockify
          git clone --depth 1 https://github.com/novnc/noVNC
          ./noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 6901 &

      - name: Establish tunnel
        id: tunnel
        uses: anyvm-org/cf-tunnel@v0
        with:
          protocol: http
          port: 6901

      - name: URL
        run: |
          echo "::notice title=Remote Desktop URL::https://${{ steps.tunnel.outputs.server }}"

      - name: Keep alive
        run: sleep 21600