name: macOS Browser Remote Desktop

on:
  workflow_dispatch:
    inputs:
      password:
        description: 'Password'
        required: true

jobs:
  remote-desktop:
    runs-on: macos-latest
    timeout-minutes: 360

    steps:
      - name: Enable Apple VNC
        run: |
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -allowAccessFor -allUsers -privs -all
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -configure -clientopts -setvnclegacy -vnclegacy yes \
            -setvncpw -vncpw "${{ github.event.inputs.password }}"
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -restart -agent -console
          sudo /System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart \
            -activate

      - name: Start novnc
        run: |
          git clone https://github.com/novnc/noVNC.git
          ./noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 6901 &

      - name: Establish tunnel
        id: tunnel
        uses: anyvm-org/cf-tunnel@v0
        with:
          protocol: http
          port: 6901

      - name: URL
        run: |
          echo "::notice title=Remote Desktop URL::https://${{ steps.tunnel.outputs.server }}"

      - name: Keep alive
        run: sleep 21600