name: NW.js Mixed Context Runner Copy

on:
  workflow_dispatch:
    inputs:
      os:
        description: "OS to run on"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  run-nwjs:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/checkout@main
      - name: Install NW.js
        run: npm install --no-save nw@0.113.0

      - name: Run app
        run: npx nw .