name: Remote Desktop

on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        type: choice
        required: true
        default: 'windows-latest'
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest

defaults:
  run:
    shell: bash

jobs:
  remote:
    runs-on: ${{ github.event.inputs.os }}
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm install

      - name: Create Tunnel
        id: tunnel
        uses: anyvm-org/cf-tunnel@v0
        with:
          protocol: http
          port: 8080

      - name: URL
        run: |
          echo "https://${{ steps.tunnel.outputs.server }}"
          npm run start
