name: Remote Desktop

on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        type: choice
        required: true
        default: 'windows-latest'
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest

defaults:
  run:
    shell: bash

env:
  DISPLAY: ":0"
  PORT: "8080"

jobs:
  remote:
    runs-on: ${{ github.event.inputs.os }}
    timeout-minutes: 360

    steps:
      - name: Copy repository into PC
        uses: actions/checkout@main

      - name: Install Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '**/requirements.txt'

      - name: Setup Ubuntu desktop GUI
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends xorg xfce4 xfce4-goodies yaru-theme-gtk yaru-theme-icon ubuntu-wallpapers xvfb

          Xvfb "${DISPLAY}" -screen 0 1920x1080x24 &

          # sleep 2

          xfconf-query -c xsettings -p /Net/ThemeName -s "Yaru"
          xfconf-query -c xfwm4 -p /general/theme -s "Yaru"
          xfconf-query -c xsettings -p /Net/IconThemeName -s "Yaru"

          xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -n -t string -s "/usr/share/backgrounds/warty-final-ubuntu.png"
          xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/image-style -n -t int -s 5

          startxfce4 &

      - name: Install server dependencies
        run: |
          pip install -r requirements.txt

      - name: Establish tunnel
        id: tunnel
        uses: anyvm-org/cf-tunnel@v0
        with:
          protocol: http
          port: ${{ env.PORT }}

      - name: Start server
        run: |
          echo "https://${{ steps.tunnel.outputs.server }}"
          python3 main.py # -u for logs
