name: Remote Desktop

defaults:
  run:
    shell: bash --noprofile --norc -euo pipefail {0}

on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating system'
        type: choice
        required: true
        default: 'windows-latest'
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest

jobs:
  remote:
    runs-on: ${{ github.event.inputs.os }}
    timeout-minutes: 360
    permissions:
      statuses: write

    steps:
      - name: Copy repository into PC
        uses: actions/checkout@main
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Create Linux virtual screen
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            lxqt \
            openbox \
            dbus-x11 \
            xvfb \
            libxrandr-dev

          read -r DISPLAY_NUMBER < <(exec Xvfb -displayfd 1)

          export DISPLAY=":$DISPLAY_NUMBER"
          echo "DISPLAY=$DISPLAY" >> "$GITHUB_ENV"
          echo "ELECTRON_DISABLE_SANDBOX=1" >> $GITHUB_ENV

          startlxqt &

      - name: Create Windows virtual screen
        if: runner.os == 'Windows'
        run: |
          winget install -e --id=Parsec.ParsecVDD

      - name: Start server
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          npm install
          npm start
