name: NW.js Mixed Context Runner

on:
  workflow_dispatch:
    inputs:
      os:
        description: "OS to run on"
        required: true
        default: "ubuntu-latest"
        type: choice
        options:
          - ubuntu-latest
          - macos-latest
          - windows-latest

jobs:
  run-nwjs:
    runs-on: ${{ github.event.inputs.os }}

    steps:
      - uses: actions/checkout@main

      - name: Setup Ubuntu display
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xterm

          read -r DISPLAY_NUMBER < <(exec Xvfb -displayfd 1)
          echo "DISPLAY=:$DISPLAY_NUMBER" >> "$GITHUB_ENV"
          xterm &

      - run: npx nw .
