name: Remote Desktop

on: 
  workflow_dispatch:
    inputs:
      os:
        description: 'OS'
        type: choice
        required: true
        default: 'windows-latest'
        options:
          - windows-latest
          - ubuntu-latest
          - macos-latest

defaults:
  run:
    shell: bash

jobs:
  remote:
    runs-on: ${{ github.event.inputs.os }}
    timeout-minutes: 360
    env:
      PORT: 8080

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install
        run: |
          npm install -g nw
          npm ci

      - name: Create Tunnel
        id: tunnel
        uses: anyvm-org/cf-tunnel@v0
        with:
          protocol: http
          port: ${{ env.PORT }}

      - name: URL
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          NODE_OPTIONS: --unhandled-rejections=strict
          PUBLIC_URL: https://${{ steps.tunnel.outputs.server }}
        run: |
          nw .
