name: RustDesk

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest

jobs:
  rustdesk:
    runs-on: ${{ github.event.inputs.os }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Get latest RustDesk version
        id: rustdesk
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(gh release view --repo rustdesk/rustdesk --json tagName -q '.tagName')
          echo "download_prefix_path=https://github.com/rustdesk/rustdesk/releases/download/${VERSION}/rustdesk-${VERSION}-x86_64" >> $GITHUB_OUTPUT

      - name: Linux setup
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            xvfb \
            xfce4 \
            xfce4-goodies \
            dbus-x11

          curl -Lo rustdesk.deb "${{ steps.rustdesk.outputs.download_prefix_path }}.deb"
          sudo apt install -fy ./rustdesk.deb

          PIPE=$(mktemp -u)
          mkfifo "$PIPE"
          Xvfb -displayfd 3 -screen 0 1920x1080x24 3>"$PIPE" &
          export DISPLAY=:$(head -1 "$PIPE")
          rm "$PIPE"
          dbus-launch startxfce4 &

          echo "rustdesk=rustdesk" >> $GITHUB_ENV

      - name: Windows setup
        if: runner.os == 'Windows'
        run: |
          curl -Lo rustdesk.exe "${{ steps.rustdesk.outputs.download_prefix_path }}.exe"
          ./rustdesk.exe --silent-install
          echo "rustdesk=./rustdesk.exe" >> $GITHUB_ENV

      - name: MacOS setup
        if: runner.os == 'macOS'
        run: |
          wget -qO rustdesk.dmg "${{ steps.rustdesk.outputs.download_prefix_path }}.dmg"
          hdiutil attach rustdesk.dmg -quiet
          VOLUME=$(ls /Volumes | grep -i rustdesk)
          cp -r "/Volumes/${VOLUME}/RustDesk.app" /Applications/
          hdiutil detach "/Volumes/${VOLUME}" -quiet
          echo "rustdesk=/Applications/RustDesk.app/Contents/MacOS/rustdesk" >> $GITHUB_ENV

      - name: Start rustdesk
        run: |
          rustdesk --service
          rustdesk --get-id
          sleep 21600