name: Inline NW.js Test

on:
  workflow_dispatch:

jobs:
  run-app:
    runs-on: macos-latest

    steps:
      # Step 1: Initialize an empty directory structures (Skipping checkout since we build it here)
      - name: Create Project Files
        run: |
          # 1. Create the package.json file inline
          cat << 'EOF' > package.json
          {
            "name": "nw-demo",
            "version": "0.0.1",
            "main": "index.html"
          }
          EOF

          # 2. Create the index.js file inline
          cat << 'EOF' > index.html
            <!DOCTYPE html>
            <html>
              <head>
                <title>Hello World!</title>
                <script>
                console.log("A")
                </script>
              </head>
              <body>
                <h1>Hello World!</h1>
                We are using node.js <script>document.write(process.version)</script>.
              </body>
            </html>
          EOF

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install the NW.js package declared in our inline package.json
      - name: Install NW.js
        run: npm install nw -y

      # Step 4: Setup virtual display and execute
      - name: Run NW.js App Headless
        run: |
          npx nw .
