name: Inline NW.js Test

on:
  workflow_dispatch:

jobs:
  run-app:
    runs-on: macos-latest

    steps:
      - name: Create Project Files
        run: |
          cat << 'EOF' > package.json
          {
            "name": "nw-demo",
            "version": "0.0.1",
            "main": "index.html"
          }
          EOF

          cat << 'EOF' > index.html
            <!DOCTYPE html>
            <html>
              <head>
                <title>Hello World!</title>
                <script>
                console.log("A")
                </script>
              </head>
              <body>
                <h1>Hello World!</h1>
                We are using node.js <script>document.write(process.version)</script>.
              </body>
            </html>
          EOF

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NW.js
        run: npm install --global nw

      - name: Run NW.js App Headless
        run: |
          nw package.json
