name: Check OS Security Settings

on: [push, workflow_dispatch]

jobs:
  check-windows:
    name: Check Windows Driver Signature Enforcement
    runs-on: windows-latest
    steps:
      - name: Check Signature Enforcement Status
        shell: pwsh
        run: |
          # Get the current Driver Signature Enforcement policy status
          $status = (Get-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\CI\Policy")."VerifiedSignatures"
          
          Write-Host "VerifiedSignatures registry value: $status"
          if ($status -eq 0) {
              Write-Host "Driver signature enforcement is disabled (Unsigned drivers are allowed)."
          } else {
              Write-Host "Driver signature enforcement is enabled (Unsigned drivers are NOT allowed)."
          }

  check-macos:
    name: Check macOS SIP
    runs-on: macos-latest
    steps:
      - name: Check System Integrity Protection (SIP)
        run: |
          # Check SIP status using the built-in csrutil
          sip_status=$(csrutil status)
          echo "SIP Status: $sip_status"
          
          if [[ "$sip_status" == *"status: enabled"* ]]; then
            echo "System Integrity Protection is enabled."
          else
            echo "System Integrity Protection is disabled."
          fi
