name: Check System Security Settings
on: [push, pull_request]

jobs:
  check-windows:
    name: Check Windows TestSigning
    runs-on: windows-latest
    steps:
      - name: Check if TESTSIGNING is enabled
        run: |
          bcdedit

  check-macos:
    name: Check macOS SIP
    runs-on: macos-latest
    steps:
      - name: Check if SIP is enabled
        run: |
          csrutil status
